### ISSUE TITLE
HW1 Review

### ISSUE THREAD

**Issue by Breucopter** [aalmufti/DAT_SF_10#1]
Hi Ali,

It's great you loaded the data and it looks like you almost got there with creating a list object of the datetimes. Instead of listing out each datetime with print (which is not a "list" object), you would need to declare the datetime_file variable as an empty list then use the .append method in the for loop.

With that it also would have been possible to insert the entire datetime list into the SQLite3 DB. The only issue with how you inserted the objects is that you inserted a tuple of 6 strings, which can't be operated on with math aggregate functions like max and min. However, Group By and Count will still work so it could still get you mostly there.

See you in class!

Best,
Justin

@ghego @craigsakuma @kebaler

**Comment by aalmufti** [comment]
Thanks Justin, that's very helpful!
